### ISSUE TITLE
error about indices[10]

### ISSUE THREAD

**Issue by chrisole** [ricsonc/ActiveVisionManipulation#1]
Hi sir, I follow ur instructions. and a error occured:

Restore path :  ../saved_weights/active_abstr/model
>>>no checkpoint file found
Evaluating:1
Found 1 GPUs for rendering. Using device 0.
Traceback (most recent call last):
  File "visualize.py", line 162, in <module>
    run(**args)
  File "visualize.py", line 111, in run
    action_noise=action_noise, actor=actor, critic=critic, memory=memory, **kwargs)
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/ddpg/testing.py", line 91, in test
    eval_obs = eval_env.reset()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/mujoco_env.py", line 99, in reset
    ob = self.reset_model()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/fakercnn_pusher.py", line 29, in reset_model
    return super().reset_model()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/bb_pusher.py", line 27, in reset_model
    rval = super().reset_model(*args, **kwargs)
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/close_pusher.py", line 54, in reset_model
    randomize_obj = False) #do not mess with the positions
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/pusher.py", line 159, in reset_model
    add_noise = add_noise)
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/reacher2d.py", line 67, in reset_model
    ob = self._get_obs()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/active_pusher.py", line 34, in _get_obs
    partial_state = super()._get_obs()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/fakercnn_pusher.py", line 42, in _get_obs
    obs = super()._get_obs()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/oc_pusher.py", line 26, in _get_obs
    obj_pos = self._get_obj_for_obs()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/bb_pusher.py", line 34, in _get_obj_for_obs
    bbox = self._get_obj_bbox()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/fakercnn_pusher.py", line 94, in _get_obj_bbox
    return self._get_obj_bbox_from_rcnn()
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/envs/fakercnn_pusher.py", line 66, in _get_obj_bbox_from_rcnn
    rcnn_out = self.rcnn.detect([rgb], verbose = 0)[0]
  File "/home/chrisole/pro/ActiveVisionManipulation-master/HER/rcnn/Mask_RCNN/model.py", line 2368, in detect
    self.keras_model.predict([molded_images, image_metas], verbose=0)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training.py", line 1169, in predict
    steps=steps)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/training_arrays.py", line 294, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/chrisole/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[10] = 16355 is not in [0, 16128)
	 [[{{node ROI/GatherV2_2}}]]

It looks that the size of indices[10] is out of scope. Could u please tell me how to solve it?

**Comment by ricsonc** [comment]
This issue was resolved over email: problem caused by using a different version of keras.
